// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShopRepo is an autogenerated mock type for the ShopRepo type
type ShopRepo struct {
	mock.Mock
}

// GetCost provides a mock function with given fields: name
func (_m *ShopRepo) GetCost(name string) (int, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCost")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShopRepo creates a new instance of ShopRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShopRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShopRepo {
	mock := &ShopRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
