// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "merch/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

// AddUser provides a mock function with given fields: ctx, username, id
func (_m *UserUseCase) AddUser(ctx context.Context, username string, id string) (int, error) {
	ret := _m.Called(ctx, username, id)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int, error)); ok {
		return rf(ctx, username, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int); ok {
		r0 = rf(ctx, username, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInfo provides a mock function with given fields: ctx, id, username
func (_m *UserUseCase) GetInfo(ctx context.Context, id int, username string) (entity.User, []entity.CoinHistory, error) {
	ret := _m.Called(ctx, id, username)

	if len(ret) == 0 {
		panic("no return value specified for GetInfo")
	}

	var r0 entity.User
	var r1 []entity.CoinHistory
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (entity.User, []entity.CoinHistory, error)); ok {
		return rf(ctx, id, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) entity.User); ok {
		r0 = rf(ctx, id, username)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) []entity.CoinHistory); ok {
		r1 = rf(ctx, id, username)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]entity.CoinHistory)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, string) error); ok {
		r2 = rf(ctx, id, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Purchase provides a mock function with given fields: ctx, id, username, item
func (_m *UserUseCase) Purchase(ctx context.Context, id int, username string, item string) error {
	ret := _m.Called(ctx, id, username, item)

	if len(ret) == 0 {
		panic("no return value specified for Purchase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = rf(ctx, id, username, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transfer provides a mock function with given fields: ctx, amount, fromUserID, fromUser, toUser
func (_m *UserUseCase) Transfer(ctx context.Context, amount int, fromUserID int, fromUser string, toUser string) error {
	ret := _m.Called(ctx, amount, fromUserID, fromUser, toUser)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) error); ok {
		r0 = rf(ctx, amount, fromUserID, fromUser, toUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
